apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_HOST: postgres
  POSTGRES_DB: keycloak
  KEYCLOAK_URL: "http://keycloak:8080/"
  REACT_APP_KEYCLOAK_URL: "http://keycloak:8080/"
  REACT_APP_KEYCLOAK_REALM: main
  REACT_APP_KEYCLOAK_CLIENT_ID: frontend